ERROR:Internal Server Error: /step
Traceback (most recent call last):
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 858, in step_by_step
    answer = stepping(views.Base.code_line1[views.Base.vari])
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 951, in stepping
    i_type[count_i].getsdi(x)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/I_type.py", line 115, in getsdi
    self.dest, self.src1, self.src2 = x.split(",")
ValueError: not enough values to unpack (expected 3, got 1)
ERROR:Internal Server Error: /execute
Traceback (most recent call last):
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 25, in index
    result, success = execute(whole_code)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 150, in execute
    i_type[count_i].getsdi(x)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/I_type.py", line 115, in getsdi
    self.dest, self.src1, self.src2 = x.split(",")
ValueError: not enough values to unpack (expected 3, got 1)
ERROR:Internal Server Error: /execute
Traceback (most recent call last):
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 25, in index
    result, success = execute(whole_code)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 150, in execute
    i_type[count_i].getsdi(x)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/I_type.py", line 115, in getsdi
    self.dest, self.src1, self.src2 = x.split(",")
ValueError: not enough values to unpack (expected 3, got 1)
ERROR:Internal Server Error: /execute
Traceback (most recent call last):
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 25, in index
    result, success = execute(whole_code)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 150, in execute
    i_type[count_i].getsdi(x)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/I_type.py", line 115, in getsdi
    self.dest, self.src1, self.src2 = x.split(",")
ValueError: not enough values to unpack (expected 3, got 1)
ERROR:Internal Server Error: /execute
Traceback (most recent call last):
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 25, in index
    result, success = execute(whole_code)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 150, in execute
    i_type[count_i].getsdi(x)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/I_type.py", line 115, in getsdi
    self.dest, self.src1, self.src2 = x.split(",")
ValueError: not enough values to unpack (expected 3, got 1)
INFO:Dumped Hex: ['0x00400293']
ERROR:Internal Server Error: /execute
Traceback (most recent call last):
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 25, in index
    result, success = execute(whole_code)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/Simulator_buttons.py", line 150, in execute
    i_type[count_i].getsdi(x)
  File "/home/bodhi/Repositories/Merl-UIT-Simulator/RISCV/r5pythonversion/r5pythonversion/I_type.py", line 115, in getsdi
    self.dest, self.src1, self.src2 = x.split(",")
ValueError: not enough values to unpack (expected 3, got 1)
